GET http://localhost:3000

###
GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjgwOTc1NTIsImV4cCI6MTY2ODA5ODE1Mn0.Afnqvgzg-Ut5ljqGRMxkCm3qeAAp23tQcfuyF97hbdmIN_eGXimrJjeMaWufLNus2uhrM7K6kI-KhIZ0fsQLUG6pdsOhuhMhIoayKprhK_oSJxClPy8G_Viefw24bb29Yea7poTROMwwiEriKVgRstv09qRS9RUTKwoA9-9BRFVWKg27pGeiRcq27vbidqEv0gYgtfPZ2AeQh3CLe2oWSzvf3eKj7w-pNF_SdA2Ex1K4AyyRXtjd54dGLIDiG9B4dAHr3FHTISSa0NQRHk0cvVAXmmsmRH2NAnZA4DmdcDJo4YDFgnHfezhajX1dW_EnzapP7k41jCgziKkEOAbxIGt1Q9NHbJKGnKlRmPuH9XvCcnGTQ8ISQTtHbFZgrwwHnX-sO5V4khnUTXjidWl3apsbDu67avnwyy_dbMQHSin8ZUN9fq1_Jf9CbucKzJr8aog4uKMqJOXvh9P3i3lUgGeOH3I8NzF_quWwez_DGbLUvu-0qTUxJpfsEDm2mpO8
